### PR TITLE
fixed misspells in the docs

### PR DESCRIPTION
**Pull request by huyndao**
Hi there, 

Thank you for a wonderful project / tool.
I fixed some spelling mistakes in the documentations, no code changes were made, please review and merge accordingly.

Huy

### CODE REVIEW

**Comment by huyndao** [comment]
@jonnor any issues regarding approving / merging my PR?

Thanks!

**Comment by jonnor** [comment]
Hi @huyndao and thank you for this contribution.

I must have missed a notification about the pull request when it was created.

The changes look great.  Accepted and merged now. Thanks!

**Comment by jonnor** [comment]
There appears to be a build failure with the documentation on readthedocs, going back around 1 month. So that needs to be resolved before your changes are visible there.

**Comment by jonnor** [comment]
Found and fixed the issue with the docs build, https://github.com/readthedocs/readthedocs.org/issues/10787

Your changes are now live @huyndao - thanks again :)

**Pull request merged**
