### PR TITLE
Added support for Regression Models

### PR DESCRIPTION
**Pull request by SaverioMonaco**
I added support for regression models for a university project I worked for.
 
I made a copy of the file trees.py called regressor_trees.py that has been modified to support these models.

### CODE REVIEW

**Comment by jonnor** [comment]
Hi @SaverioMonaco - thank you for this! Regression has been requested by several others in #31 and #41 .

To integrated it into the main version we would need to avoid copying all of the trees.py module. Instead the existing module should be modified to support both regression and classification, with minimal divergence in codepaths between the two cases.
We also need to have a few tests, to ensure that the implementation is correct. See tests/test_trees.py for examples.

Would you be interested in making these changes, so we could integrate this?

**Comment by SaverioMonaco** [comment]
I would like to add the support for regression properly, however it might take some time due to my exams.

**Comment by jonnor** [comment]
Thats great! Best of luck on your exams :)

**Comment by jonnor** [comment]
Hi @SaverioMonaco - are you still interested in working on this?

**Comment by jonnor** [comment]
This has now been implemented in #54 - thanks a lot for the inspiration @SaverioMonaco

**Pull request closed without merging**
